# Generated by Django 3.1 on 2020-09-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passebger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passebger',
            new_name='Passenger',
        ),
    ]
